name: parser_combinator
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0-154.0.dev <3.0.0'


dependencies:
  path: ^1.8.0
  utils: ^2.0.0-nullsafety.1

dev_dependencies:
  lints: ^1.0.0
